name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - name: Install dependencies
      run: sudo apt-get install -y pkg-config libwayland-dev
    - name: Build
      run: |
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig"
        cargo build --verbose
